### ISSUE TITLE
Add language switcher to topbar

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#1]
![image](https://cloud.githubusercontent.com/assets/883920/16554682/09c2a496-41d9-11e6-966a-bf128d80d4a8.png)

**Comment by michelesbw** [comment]
FYI That is "Language selector" plugin by Coldtrick

**Comment by juho-jaakkola** [comment]
Does the plugin have some special features that we need? Or is it enough if I simply add flag icons that change the UI language?

**Comment by michelesbw** [comment]
It has additional features (minimum language completeness to automatically enable a language+flag, language autodetect for non.logged in users)
