### ISSUE TITLE
Invite friends link/option missing in Friends page (screenshot)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#11]
Even better, in addition to the link in sidebar's contextual menu I think a big orange button on top of the main left column (just like "Add new blog post" or any other entity) "Invite friends" would help a lot

![friends](https://cloud.githubusercontent.com/assets/5203511/16558268/b81b1932-41e4-11e6-9de3-597d2d5ce801.png)

**Comment by juho-jaakkola** [comment]
The link is not being displayed because registration is currently disabled in the test environment.

Let's get back to the button idea after the site has been successfully upgraded.

**Comment by michelesbw** [comment]
Ah ok, sorry.
