### ISSUE TITLE
Profile page layout

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#12]
What are the minimum requirements for the profile page?

There may be a very big difference in needed work between:
 - Making it look good but not identical to the old version
 - Trying to make it look exactly like the old version

Current goals:
 - [x] Cover image at top
 - [x] Profile info in left column below cover image area
 - [x] Activity feed in left column below profile info
 - [x] Owner menu in right column under cover image area
 - [x] Three widget columns at the bottom of the page

**Comment by michelesbw** [comment]
As minimum requirements to upgrade I would say:

- Profile cover at the top (not necessarily as background of profile avatar, we can leave this as it is now on beta);
- main left column as in the rest of the site (profile info just below cover and then activity widget) and right column with owner menu and then widgetizable

**Comment by juho-jaakkola** [comment]
I got the profile cover image uploading to work with the new image API. I still need to implement the cropping and then naturally displaying the image.

**Comment by michelesbw** [comment]
Nice, never doubted you could :)

**Comment by juho-jaakkola** [comment]
The basic layout has been added, so closing.

**Comment by michelesbw** [comment]
Cover photo cropping does not work. See how different and not nice looking is https://beta.socialbusinessworld.org/profile/michele compared to https://socialbusinessworld.org/profile/michele

**Comment by juho-jaakkola** [comment]
Well, the cropping works, but there's some extra stuff added by other plugins. Bagdes is seems?

**Comment by michelesbw** [comment]
I tried to crop the image and saved with apparenty no issue but the profile page still shows the full uploaded image. Don't know if the issue is caused by other plugins, sorry.

**Comment by juho-jaakkola** [comment]
Ah, indeed. I made a fix for Elgg core, but apparently I didn't yet upgrade the patched version to beta.

**Comment by juho-jaakkola** [comment]
Installed to beta.
