### ISSUE TITLE
Html email handler plugin's footer mods

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#18]
**Remove "powered by elgg**" in notification emails in /mod/html_email_handler/views/default/html_email_handler/notification/body.php

Delete:
```html
<a href="http://www.elgg.org/" id="notification_footer_logo">
    <img src="<?php echo $vars["url"]; ?>_graphics/powered_by_elgg_badge_drk_bckgnd.gif" />
</a>
```

Add before this:
```html
<div id="notification_footer">
```
..the following:
```html
<p></p><p style="text-align: center;">SBW relies on your <a href="https://shop.socialbusinessworld.org/en/13-ethical-products-entire-catalogue">ETHICAL SHOPPING</a> at our Marketplace and your DONATIONS <a href="https://www.paypal.me/socialbusinessworld">via Paypal</a> or <a href="https://tag.satispay.com/sbworld">via Satispay</a>. See <a href="https://socialbusinessworld.org/donation">latest Donators</a>. <strong>Via banktransfer</strong> to: Social Business World, Ethic Bank (Banca Etica), Branch: Ancona (Italy) IBAN: IT90O0501802600000000151909 BIC/SWIFT: CCRTIT2T84A. Consider supporting us now. <strong>Thank you!</strong></p>
```

**Comment by juho-jaakkola** [comment]
Can you clean this up? I'm not completely sure what exactly should be done.

You can add code snippets by adding three backticks ``` on the line before and after the code.

```
    ```
    code here between
    the two backtick lines
    ```
```

**Comment by michelesbw** [comment]
Ok done, thanks for teaching me but please not this is "my code" hehehe so doesn't mean it's correct or still valid in new plugin's version. Take it at our own risk :D

**Comment by juho-jaakkola** [comment]
Now that I tested adding the text, I realized I would not want to see that message in every notification sent by the system. It would in fact be quite annoying.

IMO having it in sidebar and footer are enough. Having it in the notification emails is too intruding.

**Comment by michelesbw** [comment]
Well, I agree but it's one more way to have users know about how to support us...any other ideas?

**Comment by juho-jaakkola** [comment]
The fact that they're receiving notifications means that they have already registered to the site. So every time they click a link in the notification, they end up to the site and see the donation requests there.

I would close this for now, and get back to it once we're upgraded to Elgg 2 and have taken care of all the other missing features.

**Comment by juho-jaakkola** [comment]
Let's close in favor of: https://github.com/sbwtech/sbw/issues/47

**Comment by michelesbw** [comment]
Ok.Luca's opinion would also help. But at least let's remove the elgg logo in notifications. This is even more confusing to users.
