### ISSUE TITLE
[mobile theme]: Differences with current theme

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#21]
- [ ] icons (main menu and dashboard) missing when logged out

- [ ] replace logo with favicon

- [ ] flags missing

- [ ] only display user avatar, not also name

- [ ] move right sidebar inside main menu above main site's links

- [ ] when scrolling sidebar the tap often moves main body instead of sidebar

- [ ] first option in main menu "Blog" is barey readable and clickable

**Comment by juho-jaakkola** [comment]
I moved each of these to their own issues. Otherwise the discussion about them becomes a mess.
