### ISSUE TITLE
Iconize main menu and owner block

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#23]
Like here
![iconmenu](https://cloud.githubusercontent.com/assets/5203511/16872178/70ef8a48-4a8b-11e6-826d-31d420e0b2f8.jpg)

**Comment by michelesbw** [comment]
This would be a nice set of icons IMO:

MAIN MENU ICONS

ACTIVITY http://fontawesome.io/icon/globe
MARKETPLACE http://fontawesome.io/icon/leaf
BOOKMARKS Same as in Sidebar
THE WIRE http://fontawesome.io/icon/pencil-square-o
GROUPS http://fontawesome.io/icon/circle-o
FILES http://fontawesome.io/icon/files-o/
PAGES http://fontawesome.io/icon/file-text-o
MEMBERS same as friend requests
BLOGS Same as Hypewall extended
VIDEOS Same as Hypewall extended
EVENTS Same as Hypewall extended
POLLS Same as Hypewall extended
PHOTOS Same as Hypewall
FAQ http://fontawesome.io/icon/question-circle-o 
SCHEDULING http://fontawesome.io/icon/calendar-check-o
PADS http://fontawesome.io/icon/wpforms
DISCUSSIONS http://fontawesome.io/icon/comments-o/
TRANSLATION EDITOR http://fontawesome.io/icon/language
DASHBOARD Same as in Topbar (when users are logged in)

ADDITIONAL ICONS FOR OWNER BLOCK (OWNER MENU?)
PHOTO ALBUMS http://fontawesome.io/icon/picture-o
WALL http://fontawesome.io/icon/bullhorn
MY GROUPS http://fontawesome.io/icon/check-circle-o
GROUPS I OWN http://fontawesome.io/icon/dot-circle-o/

**Comment by feroda** [comment]
WOW, I like very much this minimized menu by ureka!
(sorry for the OT, I am working on the icons)

![minimized menu](https://cloud.githubusercontent.com/assets/232176/19014262/dc5eeac2-87e8-11e6-9aca-1a56487fea7f.png)

**Comment by michelesbw** [comment]
Not OT comment. I also like it a lot but at the end I think it is too invasive and "steals" space to the page.
I have now added all missing links to icons, sorry if my previous definitions were confusing.

**Comment by michelesbw** [comment]
Thankd for the commit! :) For some reason only FAQ icon is not showed. Let's keep this issue open as reminder to also iconize owner block, when we'll decide/have time to, which is the only one immediately visible to users :)
