### ISSUE TITLE
Replace logo with favicon in mobile

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#26]
Moved from #21

**Comment by juho-jaakkola** [comment]
What does this mean? Favicons are used only in the browser tabs etc, not in the actual content area.

**Comment by michelesbw** [comment]
Desktop has full logo, mobile has a smaller logo (square, different) which we also use as favicon. If you check and compair both mobile's topbar (current/beta) you'll see

**Comment by juho-jaakkola** [comment]
I think we could even use the same logo now that language picker is visible only to anonymous users:

![image](https://cloud.githubusercontent.com/assets/883920/16957391/d26f411c-4de4-11e6-9d8b-08af713a837c.png)

**Comment by michelesbw** [comment]
Mmm I do prefer shorter (1 line) topbar, that's too much and if we move flags it will be very nice.

**Comment by juho-jaakkola** [comment]
There's still too much stuff in there to fit the logo on the same "row" as the other elements. Do we want to remove some of the content?

I do agree that it would look nicer if everything was aligned next to each other.

**Comment by michelesbw** [comment]
That's why in mobile theme we have to use the small square logo instead of the big rectangular one

**Comment by michelesbw** [comment]
Now, having the profile name been removed, if in mobile the search box is shorter we can easily fit the square icon attached here 
![what is social business](https://cloud.githubusercontent.com/assets/5203511/17358214/0c01fc9e-5961-11e6-8417-3689a6070d9f.jpg)

**Comment by feroda** [comment]
I can try to do this today, but I would know:
1. how to correctly set in Elgg the url of a background-image in a css rule. I think I cannot pass the path of file if the file is included in the plugin since it would not benefit of the cache
2. or we can publish sbw logos in some public places so that it can be addressed by the public acccessibile urls
3. how to reload the css since theme_sbw.css seems not to be updated if I restart the web server, should I issue some command to compile a now elgg.css or so what?

thanks a lot

**Comment by juho-jaakkola** [comment]
> 1. how to correctly set in Elgg the url of a background-image in a css rule. I think I cannot pass the path of file if the file is included in the plugin since it would not benefit of the cache

I suppose we could always add both logos as `<img>`tags and toggle only their visibility through CSS. So do this twice:
https://github.com/sbwtech/theme_sbw/blob/master/views/default/page/elements/topbar_wrapper.php#L14-L22

> or we can publish sbw logos in some public places so that it can be addressed by the public acccessibile urls

The code I linked above uses `elgg_get_simplecache_url()` which automatically creates an URL that browser can cache.

> how to reload the css since theme_sbw.css seems not to be updated if I restart the web server, should I issue some command to compile a now elgg.css or so what?

The compiled CSS is stored as a file in the Elgg dataroot, so restarting apache won't affect it. Instead you must flush the caches from Elgg admin panel.

**Comment by feroda** [comment]
ok now I am admin in the beta so I can flush the caches ;)
I would like to do it all with css, not <img> tag, any clues on it? 
Anyway the option to add bot images and then load one can be good too.
