### ISSUE TITLE
Flags missing

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#27]
Moved from #21

**Comment by juho-jaakkola** [comment]
Visibility of flags are defined by the plugin language_selector plugin settings. Also remember to flush caches after editing the minimum language completeness.

@michelesbw Are you able to fix it with these instructions?

**Comment by michelesbw** [comment]
Yes but the problem was "Show language selector in header" set to NO (I don't know who/why) :)
Now have disabled it again to change flags' position as per our telegram conversation, feel free to reenabe it if needed for logged out users.

**Comment by juho-jaakkola** [comment]
FYI that setting doesn't do anything, as the theme does not have page header, but only topbar.
