### ISSUE TITLE
Only display user avatar in mobile, not also name

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#28]
Moved from #21

**Comment by juho-jaakkola** [comment]
@michelesbw Can you elaborate? Which avatar and where? A screenshot might also help.

**Comment by michelesbw** [comment]
in top bar, sorry, maybe it was clearer in more complete issue we are now splitting

**Comment by juho-jaakkola** [comment]
I do not see an avatar at all in production.

**Comment by michelesbw** [comment]
Christ! My bad Juho....that's something we always wanted to add but then didn't....very sorry, my mistake. If possible let's fit it otherwise forget it :S
