### ISSUE TITLE
When scrolling sidebar in mobile, the tap often moves main body instead of sidebar

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#30]
Moved from #21

**Comment by juho-jaakkola** [comment]
@michelesbw I'm not sure I understand this issue. Can you elaborate?

**Comment by michelesbw** [comment]
"Tapping" and scrolling on main menu often makes scroll main page, not main menu. It looks like "transparency" of main menu is not 0% so not always usable.

**Comment by juho-jaakkola** [comment]
It's completely normal from a browser to start scrolling the container element if you get to the top/bottom end of an inner element. Is this what is happening? E.g. it won't start scrolling the page unless you get to the very bottom of the main menu?

**Comment by michelesbw** [comment]
Nope. It does not scroll the main menu, it scrolls the page instead but after Ismayil's pull this is solved, seems working well now.
