### ISSUE TITLE
Profile's cover cropping does not work properly

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#33]
First, the image is not shown in cropping area (both FF and Chrome from Win10)
![cover-beta socialbusinessworld org 2016-07-26 17-48-29](https://cloud.githubusercontent.com/assets/5203511/17145243/c363d5f0-5359-11e6-87d4-7a1ce475608d.png)

After clicking on "Create your cover" the image was visualized but then the cropping rectangle was not sticky, it scrolled down with the page causing the impossibility to correctly crop the image and save.

**Comment by juho-jaakkola** [comment]
I'm not able to reproduce this. Can check whether it's still an issue?

**Comment by michelesbw** [comment]
I just tried again, not really intuitive but now works but the final result in profile page is maybe not nice, what do you think? See screenshot below.
![screenshot-beta socialbusinessworld org 2016-09-12 21-17-01](https://cloud.githubusercontent.com/assets/5203511/18449277/dcba6cf8-792e-11e6-9856-c8739b89b226.png)

**Comment by juho-jaakkola** [comment]
That should go to a separate issue as it is not related to image cropping.

**Comment by michelesbw** [comment]
Ok sorry, I thought cover height influenced points area and those buttons/spacing

**Comment by juho-jaakkola** [comment]
Well, technically you're correct. The image size is however already "decided" in Elgg 1.x version, so we cannot really change it on the fly. Or at least we would need to somehow reprocess all existing cover images to use the new aspect ratio.

**Comment by michelesbw** [comment]
No problems, hope we'll be able to improve by ... see issue here :) https://github.com/sbwtech/theme_sbw/issues/38
