### ISSUE TITLE
reduce/delete spaces and smaller icon as in screenshot attached

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#35]
<img width="281" alt="screenshotbetamobile" src="https://cloud.githubusercontent.com/assets/5203511/17492161/e519d8f6-5daa-11e6-9cbe-e375c345d658.png">

**Comment by feroda** [comment]
@michelesbw Luca Ferroni:
Great screenshot 😜 for the logo, my intention was to put it as near as possible to the profile logo

**Comment by juho-jaakkola** [comment]
I believe the spacing issues have already been fixed?

**Comment by michelesbw** [comment]
Only the vertical one marked in the screenshot as "Not needed". The others are in topbar. I guess smaller square icon would solve this issue

**Comment by juho-jaakkola** [comment]
What resolution does your mobile phone have? I do not have any problems with mine.

**Comment by michelesbw** [comment]
Don't remember but I tried different ones with Chrome's mobile visualization and it didn't look good on smaller screens let's say under 5" if I remember well

**Comment by michelesbw** [comment]
I just discovered the "self-assign" feature here on github... nice but no notifications sent out so @juho-jaakkola I guess it's important for you in this case to know that this issue won't be on your shoulders and this comment should notify you :)
