### ISSUE TITLE
Profile page needs better layout, see screenshot

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#38]
![screenshot-beta socialbusinessworld org 2016-09-12 21-17-01](https://cloud.githubusercontent.com/assets/5203511/18486850/19c91a62-79f3-11e6-8a27-5beb08feeef8.png)

**Comment by michelesbw** [comment]
This space is site-wide, should be removed or removed by 90% imho
![screenshot-beta socialbusinessworld org 2016-09-14 21-18-25](https://cloud.githubusercontent.com/assets/5203511/18526551/3f96bc1c-7ac1-11e6-96a7-5545dbfa1f91.png)

**Comment by michelesbw** [comment]
3 ideas which would solve this imho

<img width="627" alt="ideas" src="https://cloud.githubusercontent.com/assets/5203511/18542620/2b211866-7b2c-11e6-9edf-328d8dc68f77.png">

**Comment by juho-jaakkola** [comment]
I now only moved the userpoints counter to sidebar, so it won't mess up the area covered by the cover image.

Other stuff needs to be considered separately, as the layout margins affect all pages, so changes may cause unexpected results.

**Comment by michelesbw** [comment]
Hey, actually I see 2 of 3 fixes applied, also buttons are aligned to avatar's upper edge. Therefore, if you could just reduce the space as in screenshot here https://cloud.githubusercontent.com/assets/5203511/18526551/3f96bc1c-7ac1-11e6-96a7-5545dbfa1f91.png which is sitewide (logged in/out) it would be perfect. I'll reopen it not to forget it and demote it as Nice to have
