### ISSUE TITLE
Missing icons and search style on topbar (see screenshot)

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#4]
![topbaricons](https://cloud.githubusercontent.com/assets/5203511/16556052/15c6415e-41d8-11e6-9f55-cbca807ec65a.png)

**Comment by juho-jaakkola** [comment]
Is the Home icon necessary? After all the site logo will also take user to front page.

**Comment by michelesbw** [comment]
It leads to Dashboard so yes, I would add it

**Comment by juho-jaakkola** [comment]
Correction to my previous comment: Site logo takes anonymous user to front page and authenticated user to dashboard.

**Comment by michelesbw** [comment]
Auhenticated users should go to /activity clicking on logo, not dashboard, that's why the home icon is still nice to have

**Comment by juho-jaakkola** [comment]
Oh, right. I mixed up dashboard and activity page.

**Comment by michelesbw** [comment]
Please always take a look from mobiles...icons are too far from each other, resulting in a multiline topbar, not nice

**Comment by michelesbw** [comment]
Also please take a look from mobile when logged out, the icons are still missing (can't find the issue we created, the one you said it was due to piwik's unsafe links)

**Comment by juho-jaakkola** [comment]
The site will still get at lot of changes, so let's wait until we have everything in their place before tweaking the mobile version. It should be the last thing we do.

**Comment by juho-jaakkola** [comment]
Let's create separate issues for mobile version later.
