### ISSUE TITLE
Remove "Powered by Elgg" from email footer

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/theme_sbw#43]
Remove "Powered by Elgg" in notification emails by overriding:
```
views/default/html_email_handler/notification/body.php
```

**Comment by michelesbw** [comment]
MAYBE this PR fixes it https://github.com/sbwtech/theme_sbw/pull/44 :D

**Comment by juho-jaakkola** [comment]
Fixed in 55ab2310700f71b515f4c7a13b6b6ef9c227bced

**Comment by michelesbw** [comment]
Logo still there

**Comment by juho-jaakkola** [comment]
Caches hadn't been flushed. Gone now.

**Comment by juho-jaakkola** [comment]
https://beta.socialbusinessworld.org/html_email_handler/test

**Comment by michelesbw** [comment]
OK!
