### ISSUE TITLE
Footer needs better layout, replace Donators link

### ISSUE THREAD

**Issue by michelesbw** [sbwtech/theme_sbw#56]
Layout: reduce lines, centered.
Donators link to be replaced with https://socialbusinessworld.org/groups/members/74795

**Comment by feroda** [comment]
I would like to solve this simple issue, but I see it is not so straight, so I prefer to place here some notes and questions.

The footer part of the donation is in `views/default/sidebar/donate.php`  that is also used in the sidebar.

What could be the best way to proceed? I propose:

* create `views/default/page/donate-footer.php`
* transfer the content part to `elgg_echo` function in order to benefit if i18n
* use that content in `donate-footer.php` as well as in `sidebar/donate.php`

do `languages/*.php` supports html in translated strings?
should I put html inside them?

**Comment by juho-jaakkola** [comment]
> do languages/*.php supports html in translated strings?

Yes

**Comment by juho-jaakkola** [comment]
What are the differences of the footer and the sidebar? Is it that in footer, the content is centered?

**Comment by feroda** [comment]
in the footer bank info should be all on the same line, michele wants a smaller footer. I think this is the principal difference

**Comment by juho-jaakkola** [comment]
Could we use the same content in both, but simply use css to center it in the footer?
```css
.elgg-page-footer .elgg-module-aside {
    text-align: center;
}
```

**Comment by juho-jaakkola** [comment]
So we do not want to have the bank info on the same line in the sidebar?

**Comment by juho-jaakkola** [comment]
I think it might be worth trying. I 'd like to avoid duplicating the content, and instead use the same content and simply alter the appearance with css.

**Comment by feroda** [comment]
I would also prefer to avoid code duplication, but I don't know if we will achieve a good result this way. I agree with you that might be worth trying

**Comment by feroda** [comment]
Did it in https://beta.socialbusinessworld.org/activity but no luck with the css even if I pressed the big button "flush the cache" ;)

@michelesbw pls check if sidebar and footer can be good with this setup. (one line both for bank info)

**Comment by michelesbw** [comment]
Hello,
thanks for looking into it.
As above, the "see donators" link must be replaced (both in sidebar and footer) with https://socialbusinessworld.org/groups/members/74795 (donations plugin is not available anymore since we upgraded to Elgg 2).
In sidebar I don't see differences now and as for footer see screenshot below
![screenshot-beta socialbusinessworld org 2016-12-08 11-46-32](https://cloud.githubusercontent.com/assets/5203511/21007194/33d4ecf6-bd3c-11e6-9e2d-8c92954ddd2a.png)

**Comment by feroda** [comment]
I'll take a look... wonderful that is centered now ;) maybe my browser cache problem even if I started an incognito window...
